---

 - name: install package1
   action: apt name=python-software-properties

 - name: install package2
   action: apt name=software-properties-common
 
 - name: add repo
   shell: yes yes | sudo add-apt-repository ppa:nginx/stable

 - name: Update apt cache
   apt: update_cache=yes 

 - name: upgrade apt 
   apt: upgrade=dist

 - name: install nginx
   action: apt name=nginx

 - name: write nginx.conf
   template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
   notify:
     - restart nginx

 - name: delete default vhost
   action: file path=/etc/nginx/sites-enabled/default state=absent
   notify:
     - restart nginx