- name: Create the nginx ssl directory.
  file: owner=${nginx_user} mode=755 state=directory path=/etc/nginx/ssl

- name: Add server certificate.
  template: src=server.crt.j2 dest=/etc/nginx/ssl/server.crt mode=0644

- name: Add server key.
  template: src=server.key.j2 dest=/etc/nginx/ssl/server.key mode=0644