---

- name: Install koolie.
  command: npm install https://github.com/Woorank/koolie/archive/master.tar.gz -g

- name: Placing serf event handler.
  template: src=update_config_php.sh.j2 dest={{serf_install_dir}}/events/update_config.sh mode=0777
  when: koolie_php_config is defined

- name: Placing serf event handler.
  template: src=update_config_node.sh.j2 dest={{serf_install_dir}}/events/update_config.sh mode=0777
  when: koolie_php_config is not defined

- name: Placing readFiles js.
  template: src=writeConfig_node.js.j2 dest={{serf_install_dir}}/events/writeConfig.js mode=0777
  when: koolie_php_config is not defined

- name: Placing readFiles js.
  template: src=writeConfig_php.js.j2 dest={{serf_install_dir}}/events/writeConfig.js mode=0777
  when: koolie_php_config is defined

- name: Placing serf config.
  template: src=koolie_conf.json.j2 dest={{serf_install_dir}}/config/koolie_conf.json mode=0777
  notify: restart serf