---

- name: Install koolie.
  command: npm install https://github.com/Woorank/koolie/archive/master.tar.gz -g

- name: Placing serf event handler.
  template: src=update_config.sh.j2 dest={{serf_install_dir}}/events/update_config.sh mode=0777

- name: Placing readFiles js.
  template: src=readFiles.js.j2 dest={{serf_install_dir}}/events/readFiles.js mode=0777

- name: Placing serf config.
  template: src=koolie_conf.json.j2 dest={{serf_install_dir}}/events/koolie_conf.json mode=0777
  notify: restart serf