---  

- name: Update phpmyadmin config with the params
  template: src=config-db-extra.php.j2 dest=/etc/phpmyadmin/config-db-extra.php mode=0644 owner=root group=www-data

- name: Setup http authentication
  template: src=http-auth.j2 dest=/usr/share/phpmyadmin/.htaccess mode=0755 owner=www-data group=www-data

- name: Enable phpmyadmin conf to be read from apache
  lineinfile: dest=/etc/apache2/apache2.conf              
              line='Include /etc/phpmyadmin/apache.conf'

- name: Configure phpmyadmin
  lineinfile: dest=/etc/phpmyadmin/config.inc.php            
              line='require("/etc/phpmyadmin/config-db-extra.php");'

- name: Configure phpmyadmin for apache
  lineinfile: dest=/etc/phpmyadmin/apache.conf              
              insertafter='DirectoryIndex'
              line='        AllowOverride All'             
  
- name: Configure http auth user
  command: htpasswd -c -b /usr/share/phpmyadmin/.htpasswd {{http_user}} {{http_pass}}
  notify: restart apache2