---
# These tasks fetch sgml-lib DTD library.
  
- name: Fetching sgml-lib DTD library package
  get_url: url=http://validator.w3.org/sgml-lib.tar.gz dest=/opt/

- name: Unpack sgml-lib tarball.
  command: tar zxf sgml-lib.tar.gz --no-same-owner -C /opt chdir=/opt
