---

- name: add newrelic repo to apt sources
  template: src=repo.ini.j2 dest=/etc/apt/sources.list.d/newrelic.list mode=0644

- name: add newrelic key to the apt repo
  action: apt_key url=http://download.newrelic.com/548C16BF.gpg state=present  

- name: update package list
  action: apt update_cache=yes

- name: ensure newrelic-php5 is installed
  action: apt pkg=newrelic-php5 state=present

- name: update newrelic.ini with license key 
  template: src=newrelic.ini.j2 dest=/etc/php5/fpm/conf.d/newrelic.ini mode=0644
  
- name: restart php5-fpm service
  service: name=php5-fpm state=restarted