port: 3000
user: "{{app_name}}"
group: "{{app_name}}"
deploy_dir: "/var/www/{{app_name}}"
script: Server.js
monit_http_check: /
version: master
ulimit_openfiles: 1024
exec_command: "node --trace-deprecation {{deploy_dir}}/{{script}} >> /var/log/{{app_name}}.log 2>&1"
extra_node_packages:
  - git
