---

- name: update nginx.ini conf file for munin
  template: src=nginx.ini.j2 dest=/etc/nginx/sites-available/{{munin_port}}

- name: Link nginx template.
  file: src=/etc/nginx/sites-available/{{munin_port}} dest=/etc/nginx/sites-enabled/{{munin_port}} state=link  
  
- name: Generate a htpasswd file in /etc/nginx
  command: echo -e "woowoo:`perl -le 'print crypt("w00+","salt")'`" > /etc/nginx/htpasswd
  notify: restart nginx