---

- name: ensure munin is installed
  action: apt pkg=munin  state=installed
  
- name: ensure munin-node is installed
  action: apt pkg=munin-node  state=installed
  
- name: Configure munin to allow hosts.
  lineinfile: dest=/etc/munin/munin-node.conf
              regexp='^allow'
              line='allow ^.*$'
              state=present