---

- name: Apt install postgres system packages.
  apt: pkg={{item}} state=installed update-cache=yes
  with_items:
  - libpq-dev
  - python-psycopg2
  - postgresql
  - postgresql-contrib

- name: Start PostgreSQL and enable at boot
  service: name=postgresql enabled=yes state=started
  sudo_user: postgres

- name: Ensure PostgreSQL is listening on all
  lineinfile: dest=/etc/postgresql/9.1/main/postgresql.conf
   regexp='^#?listen_addresses\s*='
   line="listen_addresses = '*'"
   state=present
  sudo_user: postgres
  notify: restart postgresql

- name: Ensure PostgreSQL allows incoming TCP connections
  lineinfile: dest=/etc/postgresql/9.1/main/pg_hba.conf
             regexp='host\s+all\s+all\s+127.0.0.1/32\s+md5'
             line='host    all    all    0.0.0.0/0    md5'
             insertbefore=BOF
  sudo_user: postgres
  notify: restart postgresql

- name: ensure database is created
  action: postgresql_db db={{ dbname }} 
                        encoding='UTF-8'
                        lc_collate='en_US.UTF-8'
                        lc_ctype='en_US.UTF-8'
                        template='template0'
  sudo_user: postgres

- name: ensure user has access to database
  action: postgresql_user db={{ dbname }} user={{ dbuser }} password={{ dbpass }} priv=ALL
  sudo_user: postgres

- name: ensure user does not have unnecessary privilege
  action: postgresql_user user={{ dbuser }} role_attr_flags=NOSUPERUSER,NOCREATEDB
  sudo_user: postgres
  notify: restart postgresql
